//go:generate sh -c "sed s/{{.version}}/$(git describe --tags --always --dirty)/ number.go.tmpl > number.go"

package version

// filled by init() in number.go generated by go generate
var Number = ""
