// lintian-ssg, a static site generator for lintian tags explanations.
//
// Copyright (C) Nicolas Peugnet <nicolas@club1.fr>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//go:generate sh -c "sed s/{{.version}}/$(git describe --tags --always --dirty)/ version.go.tmpl > version.go"

package main

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"flag"
	"html/template"
	"io"
	"log"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/n-peugnet/lintian-ssg/ioutil"
	"github.com/n-peugnet/lintian-ssg/lintian"
)

const (
	outDir       = "out"
	manualPath   = "/usr/share/doc/lintian/lintian.html"
	sourceURLFmt = "https://salsa.debian.org/lintian/lintian/-/blob/%s/tags/%s.tag"
)

type TmplParams struct {
	DateYear       int
	DateHuman      string
	DateMachine    string
	BaseURL        string
	Root           string
	Version        string
	VersionLintian string
	TagList        []string
}

type ManualTmplParams struct {
	TmplParams
	Manual template.HTML
}

type TagTmplParams struct {
	TmplParams
	*lintian.Tag
	PrevName string
}

var (
	//go:embed templates/index.html.tmpl
	indexTmplStr string
	//go:embed templates/tag.html.tmpl
	tagTmplStr string
	//go:embed templates/renamed.html.tmpl
	renamedTmplStr string
	//go:embed templates/manual.html.tmpl
	manualTmplStr string
	//go:embed templates/about.html.tmpl
	aboutTmplStr string
	//go:embed templates/404.html.tmpl
	e404TmplStr string
	//go:embed assets/main.css
	mainCSS []byte
	//go:embed assets/openlogo-50.svg
	logoSVG []byte
	//go:embed assets/favicon.ico
	faviconICO []byte

	flagBaseURL     string
	flagBaseURLHelp = "URL, including the scheme and final slash, where the root of the website will be\n" +
		"located. This will be used to emit the canonical URL of each page and the sitemap."
	flagNoSitemap     bool
	flagNoSitemapHelp = "Disable sitemap.txt generation"

	// filled by init() in version.go generated by go generate
	version = ""
)

func rootRelPath(dir string) string {
	count := strings.Count(dir, "/")
	if count == 0 {
		return "./"
	}
	return strings.Repeat("../", count)
}

func createTagFile(name string) (page string, file *os.File, err error) {
	page = path.Join("tags", name+".html")
	outPath := filepath.Join(outDir, page)
	if err = os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return
	}
	file, err = os.Create(outPath)
	return
}

func renderTag(tag *lintian.Tag, params *TmplParams, tagTmpl *template.Template, renamedTmpl *template.Template, pages chan<- string, wg *sync.WaitGroup) {
	defer wg.Done()
	page, file, err := createTagFile(tag.Name)
	if err != nil {
		panic(err)
	}
	defer file.Close()
	pages <- page
	tagParams := TagTmplParams{
		TmplParams: *params,
		Tag:        tag,
	}
	tagParams.Root = rootRelPath(page)
	if err := tagTmpl.Execute(file, &tagParams); err != nil {
		panic(err)
	}
	for _, name := range tag.RenamedFrom {
		page, file, err := createTagFile(name)
		if err != nil {
			panic(err)
		}
		defer file.Close()
		pages <- page
		tagParams.Root = rootRelPath(page)
		tagParams.PrevName = name
		if err := renamedTmpl.Execute(file, &tagParams); err != nil {
			panic(err)
		}
	}
}

func writeAssets() error {
	files := []struct {
		name    string
		content io.Reader
	}{
		{"main.css", bytes.NewReader(mainCSS)},
		{"openlogo-50.svg", bytes.NewReader(logoSVG)},
		{"favicon.ico", bytes.NewReader(faviconICO)},
	}
	for _, f := range files {
		if err := ioutil.WriteFile(outDir, f.name, f.content); err != nil {
			return err
		}
	}
	return nil
}

func writeSitemap(baseURL string, pages <-chan string, wg *sync.WaitGroup) error {
	defer wg.Done()
	file, err := os.Create(filepath.Join(outDir, "sitemap.txt"))
	if err != nil {
		return err
	}
	defer file.Close()
	for page := range pages {
		if _, err := file.WriteString(baseURL + page + "\n"); err != nil {
			return err
		}
	}
	return nil
}

func discardSitemap(pages <-chan string, wg *sync.WaitGroup) {
	defer wg.Done()
	for range pages {
	}
}

func writeManual(tmpl *template.Template, params *TmplParams, path string, pages chan<- string) error {
	file, err := os.Open(manualPath)
	if err != nil {
		return err
	}
	defer file.Close()
	reader := ioutil.NewBodyFilterReader(file)
	body := bytes.Buffer{}
	if _, err := io.Copy(&body, reader); err != nil {
		return err
	}
	pages <- path
	manualParams := ManualTmplParams{*params, template.HTML(body.String())}
	manualParams.Root = rootRelPath(path)
	out := bytes.Buffer{}
	if err := tmpl.Execute(&out, &manualParams); err != nil {
		return err
	}
	return ioutil.WriteFile(outDir, path, &out)
}

func writeSimplePage(tmpl *template.Template, params TmplParams, path string, root string, pages chan<- string) error {
	file, err := os.Create(filepath.Join(outDir, path))
	if err != nil {
		return err
	}
	defer file.Close()
	if pages != nil {
		pages <- path
	}
	params.Root = root
	return tmpl.Execute(file, &params)
}

func checkErr(err error, msg ...any) {
	if err != nil {
		log.Fatalln(append(append([]any{"ERROR:"}, msg...), err)...)
	}
}

func main() {
	log.SetFlags(0)
	flag.StringVar(&flagBaseURL, "base-url", "", flagBaseURLHelp)
	flag.BoolVar(&flagNoSitemap, "no-sitemap", false, flagNoSitemapHelp)
	flag.Parse()

	checkErr(os.Mkdir(outDir, 0755), "create out dir:")

	pagesChan := make(chan string, 32)
	sitemapWG := sync.WaitGroup{}
	sitemapWG.Add(1)

	if flagBaseURL == "" || flagNoSitemap {
		go discardSitemap(pagesChan, &sitemapWG)
	} else {
		go func() {
			checkErr(writeSitemap(flagBaseURL, pagesChan, &sitemapWG), "write sitemap:")
		}()
	}

	indexTmpl := template.Must(template.New("index").Parse(indexTmplStr))
	tagTmpl := template.Must(template.Must(indexTmpl.Clone()).Parse(tagTmplStr))
	renamedTmpl := template.Must(template.Must(indexTmpl.Clone()).Parse(renamedTmplStr))
	manualTmpl := template.Must(template.Must(indexTmpl.Clone()).Parse(manualTmplStr))
	aboutTmpl := template.Must(template.Must(indexTmpl.Clone()).Parse(aboutTmplStr))
	e404Tmpl := template.Must(template.Must(indexTmpl.Clone()).Parse(e404TmplStr))

	listTagsOut := strings.Builder{}
	listTagsCmd := exec.Command("lintian-explain-tags", "--list-tags")
	listTagsCmd.Stderr = os.Stderr
	listTagsCmd.Stdout = &listTagsOut
	checkErr(listTagsCmd.Run(), "list tags:")
	listTagsStr := strings.TrimSpace(listTagsOut.String())
	listTagsLines := strings.Split(listTagsStr, "\n")

	jsonTagsArgs := append([]string{"--format=json"}, listTagsLines...)
	jsonTagsCmd := exec.Command("lintian-explain-tags", jsonTagsArgs...)
	jsonTagsCmd.Stderr = os.Stderr
	jsonTagsOut, err := jsonTagsCmd.StdoutPipe()
	checkErr(err)
	jsonTagsDecoder := json.NewDecoder(jsonTagsOut)
	checkErr(jsonTagsCmd.Start())

	date := time.Now().UTC()
	params := TmplParams{
		BaseURL:     flagBaseURL,
		DateYear:    date.Year(),
		DateHuman:   date.Format(time.RFC1123),
		DateMachine: date.Format(time.RFC3339),
		Version:     version,
		TagList:     listTagsLines,
	}

	// discard open bracket
	_, err = jsonTagsDecoder.Token()
	checkErr(err)

	tagsWG := sync.WaitGroup{}
	// while the array contains values
	for jsonTagsDecoder.More() {
		var tag lintian.Tag
		checkErr(jsonTagsDecoder.Decode(&tag))
		if params.VersionLintian == "" {
			params.VersionLintian = tag.LintianVersion
		}
		tagsWG.Add(1)
		go renderTag(&tag, &params, tagTmpl, renamedTmpl, pagesChan, &tagsWG)
	}

	// discard closing bracket
	_, err = jsonTagsDecoder.Token()
	checkErr(err)

	listTagsJSON, err := json.Marshal(listTagsLines)
	checkErr(err, "marshal listTagsLines:")
	checkErr(ioutil.WriteFile(outDir, "taglist.json", bytes.NewReader(listTagsJSON)), "write taglist:")
	checkErr(writeAssets(), "write assets:")
	checkErr(writeManual(manualTmpl, &params, "manual/index.html", pagesChan), "write manual:")
	checkErr(writeSimplePage(aboutTmpl, params, "about.html", "./", pagesChan), "write about.html:")
	checkErr(writeSimplePage(indexTmpl, params, "index.html", "./", pagesChan), "write index.html:")
	checkErr(writeSimplePage(e404Tmpl, params, "404.html", "/", nil), "write 404.html:")

	tagsWG.Wait()
	close(pagesChan)
	sitemapWG.Wait()
	if err := jsonTagsCmd.Wait(); err != nil {
		var exitError *exec.ExitError
		if errors.As(err, &exitError) {
			log.Println("WARNING: lintian-explain-tags returned non zero exit status:", exitError.ExitCode())
		} else {
			log.Println("ERROR: running lintian-explain-tags:", err)
		}
	}
}
